new_upstream_snapshot.py
Port new-upstream-snapshot to new_upstream_snapshot.py including all of
the original functionality. 

The main difference here is that this utility will not try to drop you into a
shell to walk through merge conflicts or quilt refresh failures. It will indicate
that problem and allow you to resolve the conflict/quilt issue. Then the user
can re-run the utility after the stage where the failure occurred.

Update the changelog code to use our new release numbering. 
Update docs to reference the new behavior of new_upstream_snapshot.py
Also includes tests to run through basic upstream snapshot scenario.

diff --git a/scripts/cherry-pick b/scripts/cherry-pick
--- a/scripts/cherry-pick
+++ b/scripts/cherry-pick
@@ -16,6 +16,7 @@ Usage: ${0##*/} [ options ] <<ARGUMENTS>>
 
    options:
       -h | --help  show help
+      -y | --yes Make changes without asking. Useful for scripting.
 EOF
 }
 
@@ -93,8 +94,8 @@ run_quilt() {
 }
 
 main() {
-    local short_opts="ho:v"
-    local long_opts="help,verbose"
+    local short_opts="ho:v:y"
+    local long_opts="help,verbose,yes"
     local getopt_out=""
     getopt_out=$(getopt --name "${0##*/}" \
         --options "${short_opts}" --long "${long_opts}" -- "$@") &&
@@ -108,6 +109,7 @@ main() {
         case "$cur" in
             -h|--help) Usage ; exit 0;;
             -v|--verbose) VERBOSITY=$((${VERBOSITY}+1));;
+            -y|--yes) NO_PROMPT=true;;
             --) shift; break;;
         esac
         shift;
@@ -172,20 +174,27 @@ main() {
     local message=""
     message=$(git_log_to_dch < "$fpath") ||
         { error "failed getting log entry from $fpath"; return 1; }
-    dch -i "cherry-pick $shash: $message"
-
-    dch -e || {
-        r=$?;
-        error "dch -e exited $r";
-        return $r;
-    }
+    if [ $NO_PROMPT ]; then
+        # If we're scripting this, we want the parent script
+        # controlling versions, not this one
+        dch --no-multimaint "cherry-pick $shash: $message"
+    else
+        dch -i --no-multimaint "cherry-pick $shash: $message"
+        dch -e || {
+            r=$?;
+            error "dch -e exited $r";
+            return $r;
+        }
+    fi
 
     local commit_files=""
     commit_files=( "$series" "$fpath" )
-    git diff HEAD "${commit_files[@]}"
 
-    echo -n "Commit this change? (Y/n): "
-    read answer || fail "failed to read answer"
+    if [ ! $NO_PROMPT ]; then
+        git diff HEAD "${commit_files[@]}"
+        echo -n "Commit this change? (Y/n): "
+        read answer || fail "failed to read answer"
+    fi
     case "$answer" in
         n|[Nn][oO]) exit 1;;
     esac
