Retry lxc delete command a few times to work around ZFS busy failures

diff --git a/scripts/ctool b/scripts/ctool
--- a/scripts/ctool
+++ b/scripts/ctool
@@ -965,8 +965,21 @@ git_import() {
 
 
 delete_container() {
-    lxc delete --force "$1"
+    local rc=""
+    for x in 1 2 3 4 5; do
+        # this may fail on ZFS backed systems; let's retry a few
+        # times before reporting error
+        lxc delete --force "$1" 2>/dev/null
+        rc=$?
+        if [ "$rc" = "0" ]; then
+            debug 1 "Successfully deleted container after $x attempt(s)."
+            return $rc
+        fi
+    done
+    debug 1 "Failed deleted container after $x attempts."
+    return $rc
 }
+
 
 case "${1:-}" in
     self) shift; "$@";;
