new-upstream-snapshot: require distro-info deb drop fallbak

diff --git a/scripts/new-upstream-snapshot b/scripts/new-upstream-snapshot
--- a/scripts/new-upstream-snapshot
+++ b/scripts/new-upstream-snapshot
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# Update current branch with commitish from master
+
 ORIG_TIP=""
 TEMP_D=""
 VERBOSITY=0
@@ -172,6 +174,8 @@ main() {
     local skip_branch_name_check="${SKIP_BRANCH_NAME_CHECK:-0}"
     local update_patches_only=false bug_refs_in_clog=true skip_release=false sru_bug_fillstr="SRU_BUG_NUMBER_HERE"
 
+    which distro-info || fail "Please apt-get install distro-info"
+
     local cur="" next="" 
     while [ $# -ne 0 ]; do
         cur="$1"; next="$2";
@@ -243,14 +247,11 @@ main() {
         fail "failed to read Source from changelog"
     dist=$(dpkg-parsechangelog --show-field Distribution)
 
+    # If we fail to find --series X it is because it is a devel release
+    # so set sru_ver_suff empty because we don't provide suffix on devel
     sru_ver_suff=$(distro-info --series ${cur_branch#ubuntu/} --release |
-                       awk '{printf("~%s.1", $1)}') ||
-        echo "Warning: missing distro-info package"
+                       awk '{printf("~%s.1", $1)}') || sru_ver_suff=""
 
-    if [ -z "sru_ver_suff" ]; then
-        sru_ver_suff=$(echo "$prev_pkg_ver" |
-            sed 's,.*~\([0-9.]*\)[.][0-9]$,~\1.1,')
-    fi
     [ "${sru_ver_suff}" = "${prev_pkg_ver}" ] && sru_ver_suff=""
 
     local sru_bug_string="" skip_bugs=""
